version: '3'
services:
  mariadb:
    build:  mariadb/
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: testadmin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    networks:
      - wpsite
    env_file:
      - .env
  wordpress:
    build: wordpress/
    image: wordpress
    volumes:
      - www-data:/var/www/html/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_TABLE_PREFIX: wp_table
    networks:
      - wpsite
    restart: always
  nginx:
    build: nginx/
    image: nginx
    container_name: nginx
    volumes:
      - www-data:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
      - mariadb
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db-data:
    driver_opts:
      type: none
      device: /home/mbari/data/db-data #NOTE needs full path (~ doesn't work)
      o: bind
  www-data:
    driver_opts:
      type: none
      device: /home/mbari/data/www-data #NOTE needs full path (~ doesn't work)
      o: bind
