version: '3'
services:
  mariadb:
    build:  mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    networks:
      - wpsite
    # env_file:
    #   - .env
  wordpress:
    build: wordpress/
    image: wordpress
    volumes:
      - www-data:/var/www/html/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_TABLE_PREFIX: wp_table
    networks:
      - wpsite
    restart: always
  nginx:
    build: nginx/
    image: nginx
    container_name: nginx
    volumes:
      - www-data:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - wpsite
    restart: always
  ftps:
    build: ftps/
    image: ftps
    container_name: ftps
    volumes:
      - www-data:/home/mbari
    ports:
      - "21:21"
      - "21000:21000"
    networks:
      - wpsite
    restart: always
    # environment:
    #   FTP_USERNAME: mbari
    #   FTP_PASSWORD: ftpsmbari
  adminer:
    build: adminer/
    image: adminer
    container_name: adminer
    ports:
      - 5000:5000
    depends_on:
      - nginx
    networks:
      - wpsite
    restart: always
  redis:
    build: redis/
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - nginx
    networks:
      - wpsite
    restart: always
  backup:
    container_name: backup
    build: backup/
    image: backup
    networks:
      - wpsite
    depends_on:
      - mariadb
    volumes:
      - db-data:/db-data
      - backup-data:/backup
    restart: always

  website:
    container_name: website
    build: website/
    image: website
    networks:
      - wpsite
    ports:
      - "7777:7777"
    restart: always

networks:
  wpsite:
volumes:
  db-data:
    driver_opts:
      type: none
      device: /home/mbari/data/db-data
      o: bind
  www-data:
    driver_opts:
      type: none
      device: /home/mbari/data/www-data
      o: bind
  backup-data:
    driver_opts:
      type: none
      device: /home/mbari/data/backup-data
      o: bind
