version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  wordpress-fpm:
    image: wordpress:5-fpm-alpine
    container_name: wp-fpm
    restart: always
    links: ['db']
    depends_on: ['db']
    ports: ['9001:9000']
    volumes:
      - ./mounts/www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  nginx:
    image: nginx:stable
    container_name: wp-nginx
    ports: ['8001:80']
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:
